/* eslint-disable unicorn/no-process-exit */
import esbuild from "esbuild"
import sveltePlugin from "esbuild-svelte"
import process from "node:process"
import autoPreprocess from "svelte-preprocess"
import builtins from "builtin-modules"

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository (https://github.com/mrtnbroder/obsidian-dictionary)
*/
`

const production = process.argv[2] === "production"

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["./src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "moment",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  plugins: [
    sveltePlugin({
      compileOptions: {
        css: true,
        dev: true,
      },
      preprocess: autoPreprocess(),
    }),
  ],
  outfile: "./main.js",
})

if (production) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
}
